services:
  telesync:
    build: .
    env_file:
      - .env
    volumes:
      - /tmp/telegram_saved_messages:/app/downloads
      - ./telesync_session.session:/app/telesync_session.session
    restart: unless-stopped
